### ISSUE TITLE
Invalid Operation

### ISSUE THREAD

**Issue by dominiaz** [Tedyst/HikLoad#19]
I have DVR with 16 cameras.

hikload 192.168.20.100 admin hardpassword123 --cameras=101

Traceback (most recent call last):
  File "/usr/local/bin/hikload", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/hikload/__main__.py", line 7, in main
    run(args)
  File "/usr/local/lib/python3.9/dist-packages/hikload/download.py", line 298, in run
    downloadQueue = search_for_recordings(server, args)
  File "/usr/local/lib/python3.9/dist-packages/hikload/download.py", line 148, in search_for_recordings
    channelList = server.Streaming.getChannels()
  File "/usr/local/lib/python3.9/dist-packages/hikload/hikvisionapi/_Streaming.py", line 19, in getChannels
    return hikvisionapi.getXML(self.parent, "Streaming/channels")
  File "/usr/local/lib/python3.9/dist-packages/hikload/hikvisionapi/utils.py", line 40, in getXML
    raise hikvisionapi.HikvisionException(
hikload.hikvisionapi.classes.HikvisionException: Invalid Operation

What am I doing wrong?

**Comment by Tedyst** [comment]
Can you see if ISAPI is enabled in the DVR settings? If they are enabled, can you please tell me the DVR model and the firmware version that it is running? Thanks.

**Comment by dominiaz** [comment]
Model: Internec (almost the same as hikvision)
ISAPI is enabled.

Model: i7-N39832UHV
Firmware: V3.4.92 build 170323
Code Version: V5.0 build 170228

iVMS 4200 works fine with that DVR.

**Comment by Tedyst** [comment]
If you add `--cameras=101` in the arguments, does the issue persist?

**Comment by Tedyst** [comment]
Added a check to see if Qt5 is not installed that disables the GUI. Should work now.

**Comment by dominiaz** [comment]
Disabling GUI since PyQt5 is not installed
Traceback (most recent call last):
  File "/usr/local/bin/hikload", line 33, in <module>
    sys.exit(load_entry_point('hikload==1.0.2', 'console_scripts', 'hikload')())
  File "/usr/local/bin/hikload", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/hikload-1.0.2-py3.9.egg/hikload/__main__.py", line 2, in <module>
    from .ui import main as ui_main
  File "/usr/local/lib/python3.9/dist-packages/hikload-1.0.2-py3.9.egg/hikload/ui.py", line 17, in <module>
    class downloadThread(threading.Thread):
  File "/usr/local/lib/python3.9/dist-packages/hikload-1.0.2-py3.9.egg/hikload/ui.py", line 18, in downloadThread
    def __init__(self, window: QtWidgets.QMainWindow, server: HikvisionServer, args):
NameError: name 'QtWidgets' is not defined

**Comment by Tedyst** [comment]
Now the ImportError and the NameError should be caught and dealt with. Hopefully this should work.

**Comment by Tedyst** [comment]
Did you add `--cameras 101` to the arguments?

**Comment by dominiaz** [comment]
hikload --server 192.168.20.10 --user admin --password 'password' --cameras=101
  0%|                                                                                                                                                                                          | 0/37 [00:00<?, ?it/s]

And nothing more is happening.

**Comment by Tedyst** [comment]
Maybe the cameras don't fully implement the ISAPI. Maybe with --ffmpeg it will work?

**Comment by Tedyst** [comment]
Do you have ffmpeg installed? If yes, I improved logging for the case where `--ffmpeg` is used to help debug why it isn't working for you.

**Comment by dominiaz** [comment]
ffmpeg is already the newest version (7:4.3.3-0+deb11u1).

**Comment by Tedyst** [comment]
Can you please add `--debug` to the arguments after you pull the latest commit and show me the output? Thanks.
